### ISSUE TITLE
Suggestion: Put a link of the XML in the UI

### ISSUE THREAD

**Issue by lars18th** [Barracuda09/SATPI#118]
Hi @Barracuda09 ,

Perhaps this sounds stupid, but every SAT>IP server uses a diffent path, and it's not possible to see the SSDP messages without some tools. So I suggest to add a simple link to the XML file in some part of the UI. Then it will be more easy to read it, or to copy the address. I know that in SATPI is `/desc.xml` but including the full URL will be useful.

You agree?

**Comment by Barracuda09** [comment]
Hi @lars18th 

Here you have the Description file. Do you means something like this? or really the file content?

![image](https://user-images.githubusercontent.com/6542445/110012179-90ff2d80-7d20-11eb-9f1b-43d997616a39.png)

**Comment by lars18th** [comment]
> Here you have the Description file. Do you means something like this? or really the file content?

I want the full link! So, at the left you can write something like:  "Satip Description XML (link)"
So when you "copy" the link then you can paste it directly where you need it. Or if you click on it, then the page is loaded. You don't need to print it!

You accept it?
It' simple but useful.

**Comment by Barracuda09** [comment]
@lars18th 

Could you check last commit, if this is what you mean?

**Comment by lars18th** [comment]
> Could you check last commit, if this is what you mean?

Perfect! Thank you @Barracuda09 .
