### ISSUE TITLE
Request: Print current pid list in use in Frontend Info

### ISSUE THREAD

**Issue by lars18th** [Barracuda09/SATPI#128]
Hi,

To best understand what is doing SATPI, and debugging some clients, it will be interesting if inside the "Frontend Info" page (for all type of frontends, including the virtual one) you  print the LIST OF PIDS in use.

I hope you want to implement this.
Thank you!

**Comment by Barracuda09** [comment]
Hi @lars18th 

Yes it will be usefull. But first I am trying to make SatPI more suitable in combination with VDR. Therefor I change as well #115.
Because VDR has a 'bug?' that the StreamID needs to be > 0 to request PIDS at the moment it starts with 0. But this has more impact then I expexted.

**Comment by lars18th** [comment]
Thank you for the response. I'll wait the time that it's necessary.
God job :+1:

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

This request is identical to #79. Sorry to repeat it. Then I close this. :sweat_smile:
