### ISSUE TITLE
Ports inconsistency

### ISSUE THREAD

**Issue by petrkutalek** [Barracuda09/SATPI#130]
TCP port ranges are not consistent:

* limited 1024 – 65535 and 554 – 65535 [command line](https://github.com/Barracuda09/SATPI/blob/310b4885c3c504d6e0aba42c7f42bfcc92e2906b/src/main.cpp#L197)
* allowed by minvalue 0 – 65535 [SatIP.xml](https://github.com/Barracuda09/SATPI/blob/a2b6100de3090fcd055f3f043b9a51e98e8f76d4/src/Properties.cpp#L98)

**Comment by Barracuda09** [comment]
Hi @petrkutalek 

Thanks for reporting this!

I will limit the WebIF to the command line limits.

**Comment by Barracuda09** [comment]
Should be fixed in the meantime.
