### ISSUE TITLE
Request: DiSEqC 1.1 with cascading multiswitches

### ISSUE THREAD

**Issue by Barracuda09** [Barracuda09/SATPI#150]
Use 'src=' parameter for cascading switches
src parameter should be: src >= 1 and <= 255

src bits:  7 - 6 - 5 4 3 2 - 1 0
- bits 1 0 = for the 'normal' (commited) 4 way switches
  - so in total 4 inputs
- bits 5 4 3 2 = for the DiSEqC 1.1 (uncommited) 16 way switches
  - so in total 16 inputs
- bit 6 = in which order the DiSEqC command should be send
  - 0 means _commited_ first then _uncommited_ switch commands
  - 1 means _uncommited_ first then _commited_ switch commands
- bit 7 = for sending tone burst (Monoblock LNBs) on the last command
  - 0 means do **not** send tone burst
  - 1 means send tone burst

Because src starts with 1 we should add 1 before sending it with the RTSP/HTTP request

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

This will be optional or mandatory? I ask because I can't understand how we can mix the regular 1-4 (or 1-8) supported by the specifications with your new complex mapping. Perhaps, you prefer to use the range 16 to 255 only.

**Comment by Barracuda09** [comment]
Hi @lars18th 

Thanks for you response and input.

This will only be handled in DiSEqcSwitch.cpp (or derived file). So it should be no problem (as I see it now) for the rest of the functionality.
https://github.com/Barracuda09/SATPI/blob/e9512de8cd29ba6f8308cd100a47201d6538e186/src/input/dvb/delivery/DiSEqcSwitch.cpp#L73-L80

**Comment by Barracuda09** [comment]
See: https://github.com/Barracuda09/SATPI/wiki/Setup-DiSEqC-Switches
