### ISSUE TITLE
ARM binary with libdvbcsa enabled

### ISSUE THREAD

**Issue by chilledsheep** [Barracuda09/SATPI#183]
are there any ARM binarys with libdvbcsa enabled or any E2 Image that comes with satpi with libdvbcsa enabled? because i dont have the knowledge to compile it by myself

**Comment by Barracuda09** [comment]
Hi @chilledsheep 

You could try on of these https://github.com/Barracuda09/SATPI/issues/182#issuecomment-1384455185 it should work on a _VU+ Uno 4K_ and _GigaBlue UHD Quad 4K_ and PI4

**Comment by chilledsheep** [comment]
thanks @Barracuda09 it works on my anadol multibox :)
