### ISSUE TITLE
[Feature Request] FE_ENABLE_HIGH_LNB_VOLTAGE

### ISSUE THREAD

**Issue by SaulGoodman1337** [Barracuda09/SATPI#188]
https://www.kernel.org/doc/html/latest/userspace-api/media/dvb/fe-enable-high-lnb-voltage.html?highlight=fe_enable_high_lnb_voltage#c.DTV.fe.FE_ENABLE_HIGH_LNB_VOLTAGE

**Comment by Barracuda09** [comment]
@SaulGoodman1337  I have added this, you need to update web folder as well I you like to test is.
