### ISSUE TITLE
double stop_http(); in satip.c

### ISSUE THREAD

**Issue by 9000h** [Barracuda09/SATPI#2]
stop_http();   <------ is this a double stop here??
        stop_rtsp(&rtpsession);

        // cleanup threads
        stop_http();
        if (ssdp) {
                stop_ssdp();
        }
        stop_rtp(&rtpsession);

**Comment by Barracuda09** [comment]
Uhmm yes... that should not be there.

**Comment by Barracuda09** [comment]
Is removed.
