### ISSUE TITLE
Presentation URL and UUID 42 and 43. When discovering in VU+ server capacity full

### ISSUE THREAD

**Issue by a038537** [Barracuda09/SATPI#200]
Hi,

I installed satpi and the sat>ip client. When I start the server and discover on my VU+, the server is found but the presentation url and UUID don't match and the server capacity is full.

The presentation url shows 43
the UUID shows 42

What am I doing wrong?

**Comment by Barracuda09** [comment]
Hi,

Sorry, I'm not quite sure what you mean. The url is not the same as UUID

Could you explain it a bit more (maybe with pictures?)

Thanks for you time and testing.

marc

**Comment by Barracuda09** [comment]
Thanks for replying, then I will close this.

If you encounter other problems, then please make a new issue.
