### ISSUE TITLE
SATPI does not stream anything after ~1 day

### ISSUE THREAD

**Issue by FuNK3Y** [Barracuda09/SATPI#34]
Hi Marc,

I noticed that SATPI stop streaming after ~1 day. During the day SATPI is mostly idle, about 2h of TV plus the EPG scanning (occuring everyday at 00:04 & 12:04).

This issue is pretty strange, as killing & restarting SATPI does not solve it, only a full restart of my cubox clear the error out.This does not seems to be driver/firmware related, as w_scan works fine when SATPI don't.

My best guess would be that the some parameter of the tuner (counters, status, ...) might over time get values that does not suit SATPI's expectations.

Here is the log:
0  Wed Apr  1 23:46:17.084133398 2015  6  [        Satpi.cpp:247] --- starting SatPI version: 1.5.56~gab67788 ---
1  Wed Apr  1 23:46:17.085467135 2015  6  [  InterfaceAttr.h:094] eth0: 192.168.1.22 [d0:63:b4:00:6f:fa]
2  Wed Apr  1 23:46:17.086566524 2015  7  [      Streams.cpp:113] Not the preferred DVB API version, for correct function it should be 5.5 or higher
3  Wed Apr  1 23:46:17.086661862 2015  7  [      Streams.cpp:115] Current DVB_API_VERSION: 5.4
4  Wed Apr  1 23:46:17.086732866 2015  6  [      Streams.cpp:117] Detecting frontends in: /dev/dvb
5  Wed Apr  1 23:46:17.089678350 2015  6  [      Streams.cpp:135] Frontends found: 2
6  Wed Apr  1 23:46:17.090209046 2015  6  [     Frontend.cpp:147] Frontend Name: DRXK DVB-C DVB-T
7  Wed Apr  1 23:46:17.090294718 2015  7  [     Frontend.cpp:247] Frontend Type: Cable (Annex C)
8  Wed Apr  1 23:46:17.090355388 2015  7  [     Frontend.cpp:256] Frontend Type: Unknown 18
9  Wed Apr  1 23:46:17.090412391 2015  7  [     Frontend.cpp:229] Frontend Type: Terrestrial (DVB-T)
10  Wed Apr  1 23:46:17.090471728 2015  7  [     Frontend.cpp:260] Frontend Freq: 47000000 Hz to 865000000 Hz
11  Wed Apr  1 23:46:17.090529398 2015  7  [     Frontend.cpp:261] Frontend srat: 870000 symbols/s to 11700000 symbols/s
12  Wed Apr  1 23:46:17.090614736 2015  6  [     Frontend.cpp:147] Frontend Name: DRXK DVB-C DVB-T
13  Wed Apr  1 23:46:17.090680739 2015  7  [     Frontend.cpp:247] Frontend Type: Cable (Annex C)
14  Wed Apr  1 23:46:17.090735076 2015  7  [     Frontend.cpp:256] Frontend Type: Unknown 18
15  Wed Apr  1 23:46:17.090834748 2015  7  [     Frontend.cpp:229] Frontend Type: Terrestrial (DVB-T)
16  Wed Apr  1 23:46:17.090891418 2015  7  [     Frontend.cpp:260] Frontend Freq: 47000000 Hz to 865000000 Hz
17  Wed Apr  1 23:46:17.090945088 2015  7  [     Frontend.cpp:261] Frontend srat: 870000 symbols/s to 11700000 symbols/s
18  Wed Apr  1 23:46:17.091359445 2015  6  [   RtspServer.cpp:059] Setting up RTSP server
19  Wed Apr  1 23:46:17.091630128 2015  6  [   HttpServer.cpp:075] Setting up HTTP server
20  Wed Apr  1 23:46:17.092005482 2015  6  [   SsdpServer.cpp:108] Setting up SSDP server with BOOTID: 12
21  Wed Apr  1 23:46:17.141704523 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59908 (fd: 8)
22  Wed Apr  1 23:46:17.341457745 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59910 (fd: 9)
23  Wed Apr  1 23:46:17.347433071 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59911 (fd: 10)
24  Wed Apr  1 23:46:17.347735088 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59912 (fd: 11)
25  Wed Apr  1 23:46:17.355869531 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59913 (fd: 12)
26  Wed Apr  1 23:46:17.431427983 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.119 Port 59909 (fd: 13)
27  Wed Apr  1 23:46:26.647211324 2015  6  [   SsdpServer.cpp:191] SAT>IP Client 192.168.1.20 : tries to discover the network, sending an reply
28  Wed Apr  1 23:46:26.647515341 2015  6  [   SsdpServer.cpp:191] SAT>IP Client 192.168.1.20 : tries to discover the network, sending an reply
29  Wed Apr  1 23:46:26.647799689 2015  6  [   SsdpServer.cpp:191] SAT>IP Client 192.168.1.20 : tries to discover the network, sending an reply
30  Wed Apr  1 23:46:26.898895396 2015  6  [    TcpSocket.cpp:149] HTTP Connection from 192.168.1.20 Port 59384 (fd: 14)
31  Wed Apr  1 23:46:26.899156075 2015  7  [   HttpServer.cpp:178] Client: 192.168.1.20 requesed /desc.xml
32  Wed Apr  1 23:46:26.901820204 2015  7  [    TcpSocket.cpp:085] HTTP Client 192.168.1.20: Connection closed with fd: 14
33  Wed Apr  1 23:46:42.006462860 2015  6  [    TcpSocket.cpp:149] RTSP Connection from 192.168.1.20 Port 51744 (fd: 14)
34  Wed Apr  1 23:46:42.006698540 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: SETUP rtsp://192.168.1.22/?fe=3&freq=354&sr=6900&msys=dvbc&mtype=256qam&fec=35 RTSP/1.0
35  Wed Apr  1 23:46:42.006698540 2015  7  Transport: RTP/AVP;unicast;client_port=37080-37081
36  Wed Apr  1 23:46:42.006698540 2015  7  CSeq: 1
37  Wed Apr  1 23:46:42.006698540 2015  7  --- LINE END ---
38  Wed Apr  1 23:46:42.007270572 2015  6  [      Streams.cpp:250] Found StreamID x - SessionID x - Creating new SessionID: 1702957685
39  Wed Apr  1 23:46:42.007442914 2015  6  [       Stream.cpp:064] Stream: 0, StreamClient[0] with SessionID 1702957685 for dvbc
40  Wed Apr  1 23:46:42.007622924 2015  7  [       Stream.cpp:209] Stream: 0, Parsing transport parameters...
41  Wed Apr  1 23:46:42.009242345 2015  7  [ StreamClient.cpp:043] Connection can close: 0
42  Wed Apr  1 23:46:42.009585697 2015  6  [     Frontend.cpp:475] Stream: 0, Opened /dev/dvb/adapter0/frontend0 fd: 15
43  Wed Apr  1 23:46:42.009729371 2015  7  [     Frontend.cpp:410] Stream: 0, Start tuning process...
44  Wed Apr  1 23:46:42.010401740 2015  6  [     Frontend.cpp:486] Stream: 0, Waiting on lock...
45  Wed Apr  1 23:46:42.010534748 2015  6  [     Frontend.cpp:500] Stream: 0, Not locked yet (FE status 0x0)...
46  Wed Apr  1 23:46:42.184504563 2015  6  [     Frontend.cpp:500] Stream: 0, Not locked yet (FE status 0x0)...
47  Wed Apr  1 23:46:42.240883969 2015  6  [     Frontend.cpp:500] Stream: 0, Not locked yet (FE status 0x0)...
48  Wed Apr  1 23:46:42.303012023 2015  6  [     Frontend.cpp:497] Stream: 0, Tuned and locked (FE status 0x1F).
49  Wed Apr  1 23:46:42.303522717 2015  6  [     Frontend.cpp:518] Stream: 0, Opened /dev/dvb/adapter0/dvr0 fd: 16.
50  Wed Apr  1 23:46:42.304020411 2015  6  [     Frontend.cpp:530] Stream: 0, Updating PID filters...
51  Wed Apr  1 23:46:42.304957462 2015  6  [    RtpThread.cpp:095] Stream: 0, Start   RTP stream to 192.168.1.20:37080
52  Wed Apr  1 23:46:42.305298147 2015  6  [   RtcpThread.cpp:073] Stream: 0, Start  RTCP stream to 192.168.1.20:37081
53  Wed Apr  1 23:46:42.305446822 2015  7  [   RtspServer.cpp:141] RTSP/1.0 200 OK
54  Wed Apr  1 23:46:42.305446822 2015  7  CSeq: 1
55  Wed Apr  1 23:46:42.305446822 2015  7  Session: 1702957685;timeout=60
56  Wed Apr  1 23:46:42.305446822 2015  7  Transport: RTP/AVP;unicast;client_port=37080-37081
57  Wed Apr  1 23:46:42.305446822 2015  7  com.ses.streamID: 0
58  Wed Apr  1 23:46:42.305446822 2015  7  --- LINE END ---
59  Wed Apr  1 23:46:42.306811896 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: PLAY rtsp://192.168.1.22/stream=0?addpids=0,1,16,17,18,208,209,210,219,228,238 RTSP/1.0
60  Wed Apr  1 23:46:42.306811896 2015  7  Session: 1702957685
61  Wed Apr  1 23:46:42.306811896 2015  7  CSeq: 2
62  Wed Apr  1 23:46:42.306811896 2015  7  --- LINE END ---
63  Wed Apr  1 23:46:42.307336925 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 1702957685
64  Wed Apr  1 23:46:42.307483600 2015  6  [       Stream.cpp:067] Stream: 0, StreamClient[0] with SessionID 1702957685
65  Wed Apr  1 23:46:42.307624941 2015  7  [       Stream.cpp:209] Stream: 0, Parsing transport parameters...
66  Wed Apr  1 23:46:42.308187971 2015  7  [ StreamClient.cpp:043] Connection can close: 0
67  Wed Apr  1 23:46:42.308336313 2015  6  [     Frontend.cpp:530] Stream: 0, Updating PID filters...
68  Wed Apr  1 23:46:42.308529657 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0000 - fd: 020
69  Wed Apr  1 23:46:42.308711667 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0001 - fd: 021
70  Wed Apr  1 23:46:42.308935012 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0016 - fd: 022
71  Wed Apr  1 23:46:42.309129356 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0017 - fd: 023
72  Wed Apr  1 23:46:42.309285031 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0018 - fd: 024
73  Wed Apr  1 23:46:42.309470041 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0208 - fd: 025
74  Wed Apr  1 23:46:42.309648718 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0209 - fd: 026
75  Wed Apr  1 23:46:42.309880397 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0210 - fd: 027
76  Wed Apr  1 23:46:42.310046739 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0219 - fd: 028
77  Wed Apr  1 23:46:42.310221415 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0228 - fd: 029
78  Wed Apr  1 23:46:42.310397092 2015  7  [     Frontend.cpp:547] Stream: 0, Set filter PID: 0238 - fd: 030
79  Wed Apr  1 23:46:42.311092130 2015  7  [   RtspServer.cpp:165] RTSP/1.0 200 OK
80  Wed Apr  1 23:46:42.311092130 2015  7  RTP-Info: url=rtsp://192.168.1.22/stream=0
81  Wed Apr  1 23:46:42.311092130 2015  7  CSeq: 2
82  Wed Apr  1 23:46:42.311092130 2015  7  Session: 1702957685
83  Wed Apr  1 23:46:42.311092130 2015  7  --- LINE END ---
84  Wed Apr  1 23:46:47.953643356 2015  6  [    TcpSocket.cpp:149] RTSP Connection from 192.168.1.20 Port 51745 (fd: 31)
85  Wed Apr  1 23:46:47.953891703 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: SETUP rtsp://192.168.1.22/?fe=4&freq=354&sr=6900&msys=dvbc&mtype=256qam&fec=35 RTSP/1.0
86  Wed Apr  1 23:46:47.953891703 2015  7  Transport: RTP/AVP;unicast;client_port=40120-40121
87  Wed Apr  1 23:46:47.953891703 2015  7  CSeq: 1
88  Wed Apr  1 23:46:47.953891703 2015  7  --- LINE END ---
89  Wed Apr  1 23:46:47.954398064 2015  6  [      Streams.cpp:250] Found StreamID x - SessionID x - Creating new SessionID: 0205744672
90  Wed Apr  1 23:46:47.954545405 2015  6  [       Stream.cpp:064] Stream: 1, StreamClient[0] with SessionID 0205744672 for dvbc
91  Wed Apr  1 23:46:47.954678412 2015  7  [       Stream.cpp:209] Stream: 1, Parsing transport parameters...
92  Wed Apr  1 23:46:47.956238497 2015  7  [ StreamClient.cpp:043] Connection can close: 0
93  Wed Apr  1 23:46:47.956552181 2015  6  [     Frontend.cpp:475] Stream: 1, Opened /dev/dvb/adapter1/frontend0 fd: 32
94  Wed Apr  1 23:46:47.956688188 2015  7  [     Frontend.cpp:410] Stream: 1, Start tuning process...
95  Wed Apr  1 23:46:47.957337557 2015  6  [     Frontend.cpp:486] Stream: 1, Waiting on lock...
96  Wed Apr  1 23:46:47.957457897 2015  6  [     Frontend.cpp:500] Stream: 1, Not locked yet (FE status 0x0)...
97  Wed Apr  1 23:46:48.124693012 2015  6  [     Frontend.cpp:500] Stream: 1, Not locked yet (FE status 0x0)...
98  Wed Apr  1 23:46:48.180571058 2015  6  [     Frontend.cpp:500] Stream: 1, Not locked yet (FE status 0x0)...
99  Wed Apr  1 23:46:48.242575105 2015  6  [     Frontend.cpp:497] Stream: 1, Tuned and locked (FE status 0x1F).
100  Wed Apr  1 23:46:48.243092133 2015  6  [     Frontend.cpp:518] Stream: 1, Opened /dev/dvb/adapter1/dvr0 fd: 33.
101  Wed Apr  1 23:46:48.243537490 2015  6  [     Frontend.cpp:530] Stream: 1, Updating PID filters...
102  Wed Apr  1 23:46:48.244425205 2015  6  [    RtpThread.cpp:095] Stream: 1, Start   RTP stream to 192.168.1.20:40120
103  Wed Apr  1 23:46:48.244798892 2015  6  [   RtcpThread.cpp:073] Stream: 1, Start  RTCP stream to 192.168.1.20:40121
104  Wed Apr  1 23:46:48.244951567 2015  7  [   RtspServer.cpp:141] RTSP/1.0 200 OK
105  Wed Apr  1 23:46:48.244951567 2015  7  CSeq: 1
106  Wed Apr  1 23:46:48.244951567 2015  7  Session: 0205744672;timeout=60
107  Wed Apr  1 23:46:48.244951567 2015  7  Transport: RTP/AVP;unicast;client_port=40120-40121
108  Wed Apr  1 23:46:48.244951567 2015  7  com.ses.streamID: 1
109  Wed Apr  1 23:46:48.244951567 2015  7  --- LINE END ---
110  Wed Apr  1 23:46:48.245796613 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: TEARDOWN rtsp://192.168.1.22/stream=0 RTSP/1.0
111  Wed Apr  1 23:46:48.245796613 2015  7  Session: 1702957685
112  Wed Apr  1 23:46:48.245796613 2015  7  CSeq: 3
113  Wed Apr  1 23:46:48.245796613 2015  7  --- LINE END ---
114  Wed Apr  1 23:46:48.246413980 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 1702957685
115  Wed Apr  1 23:46:48.246553321 2015  6  [       Stream.cpp:067] Stream: 0, StreamClient[0] with SessionID 1702957685
116  Wed Apr  1 23:46:48.246727331 2015  7  [ StreamClient.cpp:043] Connection can close: 1
117  Wed Apr  1 23:46:48.246881006 2015  6  [       Stream.cpp:137] Stream: 0, Teardown StreamClient[0] with SessionID 1702957685
118  Wed Apr  1 23:46:48.347108802 2015  6  [    RtpThread.cpp:107] Stream: 0, Stop   RTP stream to 192.168.1.20:37080 (Streamed 0.000 MBytes)
119  Wed Apr  1 23:46:48.547445722 2015  6  [   RtcpThread.cpp:083] Stream: 0, Stop  RTCP stream to 192.168.1.20:37081
120  Wed Apr  1 23:46:48.547597730 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0000 - fd: 020 - Packet Count: 0
121  Wed Apr  1 23:46:48.547799075 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0001 - fd: 021 - Packet Count: 0
122  Wed Apr  1 23:46:48.547950416 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0016 - fd: 022 - Packet Count: 0
123  Wed Apr  1 23:46:48.548092757 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0017 - fd: 023 - Packet Count: 0
124  Wed Apr  1 23:46:48.548235432 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0018 - fd: 024 - Packet Count: 0
125  Wed Apr  1 23:46:48.548386773 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0208 - fd: 025 - Packet Count: 0
126  Wed Apr  1 23:46:48.548529114 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0209 - fd: 026 - Packet Count: 0
127  Wed Apr  1 23:46:48.548671122 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0210 - fd: 027 - Packet Count: 0
128  Wed Apr  1 23:46:48.548834798 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0219 - fd: 028 - Packet Count: 0
129  Wed Apr  1 23:46:48.548977472 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0228 - fd: 029 - Packet Count: 0
130  Wed Apr  1 23:46:48.549131481 2015  7  [     Frontend.cpp:562] Stream: 0, Remove filter PID: 0238 - fd: 030 - Packet Count: 0
131  Wed Apr  1 23:46:48.549828519 2015  7  [   RtspServer.cpp:281] RTSP/1.0 200 OK
132  Wed Apr  1 23:46:48.549828519 2015  7  CSeq: 3
133  Wed Apr  1 23:46:48.549828519 2015  7  Session: 1702957685
134  Wed Apr  1 23:46:48.549828519 2015  7  --- LINE END ---
135  Wed Apr  1 23:46:48.550528557 2015  7  [    TcpSocket.cpp:085] RTSP Client 192.168.1.20: Connection closed with fd: 14
136  Wed Apr  1 23:46:48.550803238 2015  6  [      Streams.cpp:222] Found SessionID 1702957685 by SocketClient
137  Wed Apr  1 23:46:48.551020250 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 1702957685
138  Wed Apr  1 23:46:48.551151924 2015  6  [       Stream.cpp:067] Stream: 0, StreamClient[0] with SessionID 1702957685
139  Wed Apr  1 23:46:48.551360269 2015  6  [       Stream.cpp:129] Stream: 0, Close StreamClient[0] with SessionID 1702957685
140  Wed Apr  1 23:46:48.552066307 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: PLAY rtsp://192.168.1.22/stream=1?addpids=0,1,16,17,18,208,209,210,219,228,238 RTSP/1.0
141  Wed Apr  1 23:46:48.552066307 2015  7  Session: 0205744672
142  Wed Apr  1 23:46:48.552066307 2015  7  CSeq: 2
143  Wed Apr  1 23:46:48.552066307 2015  7  --- LINE END ---
144  Wed Apr  1 23:46:48.552795680 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 0205744672
145  Wed Apr  1 23:46:48.552955356 2015  6  [       Stream.cpp:081] Stream: 0, No StreamClient with SessionID 0205744672
146  Wed Apr  1 23:46:48.553104364 2015  6  [       Stream.cpp:067] Stream: 1, StreamClient[0] with SessionID 0205744672
147  Wed Apr  1 23:46:48.553245705 2015  7  [       Stream.cpp:209] Stream: 1, Parsing transport parameters...
148  Wed Apr  1 23:46:48.553804069 2015  7  [ StreamClient.cpp:043] Connection can close: 0
149  Wed Apr  1 23:46:48.553931742 2015  6  [     Frontend.cpp:530] Stream: 1, Updating PID filters...
150  Wed Apr  1 23:46:48.554102752 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0000 - fd: 014
151  Wed Apr  1 23:46:48.554259427 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0001 - fd: 015
152  Wed Apr  1 23:46:48.554413102 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0016 - fd: 016
153  Wed Apr  1 23:46:48.554568444 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0017 - fd: 018
154  Wed Apr  1 23:46:48.554722119 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0018 - fd: 020
155  Wed Apr  1 23:46:48.554931463 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0208 - fd: 021
156  Wed Apr  1 23:46:48.555087805 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0209 - fd: 022
157  Wed Apr  1 23:46:48.555240814 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0210 - fd: 023
158  Wed Apr  1 23:46:48.555393489 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0219 - fd: 024
159  Wed Apr  1 23:46:48.555548497 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0228 - fd: 025
160  Wed Apr  1 23:46:48.555703506 2015  7  [     Frontend.cpp:547] Stream: 1, Set filter PID: 0238 - fd: 026
161  Wed Apr  1 23:46:48.556317872 2015  7  [   RtspServer.cpp:165] RTSP/1.0 200 OK
162  Wed Apr  1 23:46:48.556317872 2015  7  RTP-Info: url=rtsp://192.168.1.22/stream=1
163  Wed Apr  1 23:46:48.556317872 2015  7  CSeq: 2
164  Wed Apr  1 23:46:48.556317872 2015  7  Session: 0205744672
165  Wed Apr  1 23:46:48.556317872 2015  7  --- LINE END ---
166  Wed Apr  1 23:46:54.004308135 2015  7  [   RtspServer.cpp:072] Data from client 192.168.1.20: TEARDOWN rtsp://192.168.1.22/stream=1 RTSP/1.0
167  Wed Apr  1 23:46:54.004308135 2015  7  Session: 0205744672
168  Wed Apr  1 23:46:54.004308135 2015  7  CSeq: 3
169  Wed Apr  1 23:46:54.004308135 2015  7  --- LINE END ---
170  Wed Apr  1 23:46:54.004920506 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 0205744672
171  Wed Apr  1 23:46:54.005060181 2015  6  [       Stream.cpp:081] Stream: 0, No StreamClient with SessionID 0205744672
172  Wed Apr  1 23:46:54.005215523 2015  6  [       Stream.cpp:067] Stream: 1, StreamClient[0] with SessionID 0205744672
173  Wed Apr  1 23:46:54.005389867 2015  7  [ StreamClient.cpp:043] Connection can close: 1
174  Wed Apr  1 23:46:54.005520542 2015  6  [       Stream.cpp:137] Stream: 1, Teardown StreamClient[0] with SessionID 0205744672
175  Wed Apr  1 23:46:54.105745687 2015  6  [    RtpThread.cpp:107] Stream: 1, Stop   RTP stream to 192.168.1.20:40120 (Streamed 0.000 MBytes)
176  Wed Apr  1 23:46:54.306111925 2015  6  [   RtcpThread.cpp:083] Stream: 1, Stop  RTCP stream to 192.168.1.20:40121
177  Wed Apr  1 23:46:54.306271935 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0000 - fd: 014 - Packet Count: 0
178  Wed Apr  1 23:46:54.306435946 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0001 - fd: 015 - Packet Count: 0
179  Wed Apr  1 23:46:54.306581621 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0016 - fd: 016 - Packet Count: 0
180  Wed Apr  1 23:46:54.306723964 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0017 - fd: 018 - Packet Count: 0
181  Wed Apr  1 23:46:54.306911642 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0018 - fd: 020 - Packet Count: 0
182  Wed Apr  1 23:46:54.307065652 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0208 - fd: 021 - Packet Count: 0
183  Wed Apr  1 23:46:54.307206994 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0209 - fd: 022 - Packet Count: 0
184  Wed Apr  1 23:46:54.307348336 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0210 - fd: 023 - Packet Count: 0
185  Wed Apr  1 23:46:54.307487011 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0219 - fd: 024 - Packet Count: 0
186  Wed Apr  1 23:46:54.307627353 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0228 - fd: 025 - Packet Count: 0
187  Wed Apr  1 23:46:54.307785697 2015  7  [     Frontend.cpp:562] Stream: 1, Remove filter PID: 0238 - fd: 026 - Packet Count: 0
188  Wed Apr  1 23:46:54.308456406 2015  7  [   RtspServer.cpp:281] RTSP/1.0 200 OK
189  Wed Apr  1 23:46:54.308456406 2015  7  CSeq: 3
190  Wed Apr  1 23:46:54.308456406 2015  7  Session: 0205744672
191  Wed Apr  1 23:46:54.308456406 2015  7  --- LINE END ---
192  Wed Apr  1 23:46:54.309568804 2015  7  [    TcpSocket.cpp:085] RTSP Client 192.168.1.20: Connection closed with fd: 31
193  Wed Apr  1 23:46:54.309777149 2015  6  [      Streams.cpp:222] Found SessionID 0205744672 by SocketClient
194  Wed Apr  1 23:46:54.309961493 2015  6  [      Streams.cpp:242] Found StreamID x - SessionID: 0205744672
195  Wed Apr  1 23:46:54.310093500 2015  6  [       Stream.cpp:081] Stream: 0, No StreamClient with SessionID 0205744672
196  Wed Apr  1 23:46:54.310310512 2015  6  [       Stream.cpp:067] Stream: 1, StreamClient[0] with SessionID 0205744672
197  Wed Apr  1 23:46:54.310436852 2015  6  [       Stream.cpp:129] Stream: 1, Close StreamClient[0] with SessionID 0205744672

Here is what TVH thinks of it:
2015-04-01 23:46:48.000 mpegts: 354MHz in Cablecom - tuning on SAT>IP DVB-C Tuner #4 (192.168.1.22)
2015-04-01 23:46:48.000 subscription: 0001: "HTTP" subscribing on "RTS Un HD", weight: 100, adapter: "SAT>IP DVB-C Tuner #4 (192.168.1.22)", network: "Cablecom", mux: "354MHz", provider: "upc", service: "RTS Un HD", profile="pass", hostname="192.168.1.119", username="", client="VLC/2.1.5 LibVLC/2.1.5"
2015-04-01 23:46:58.000 webui: Couldn't start streaming /stream/channel/5e5d62222d01b16f97b770cb62be5481, No input detected

Here is an example of w_scan:
314000: sr6900 (time: 07:44) (time: 07:45) signal ok:
        QAM_256  f = 314000 kHz S6900C999
Info: no data from NIT(actual)
322000: sr6900 (time: 07:58) (time: 07:59) signal ok:
        QAM_256  f = 322000 kHz S6900C999
Info: no data from NIT(actual)
330000: sr6900 (time: 08:11) (time: 08:12) signal ok:
        QAM_256  f = 330000 kHz S6900C999
Info: no data from NIT(actual)
338000: sr6900 (time: 08:24) (time: 08:25) signal ok:
        QAM_256  f = 338000 kHz S6900C999
Info: no data from NIT(actual)
346000: sr6900 (time: 08:38) (time: 08:39) signal ok:
        QAM_256  f = 346000 kHz S6900C999

**Comment by Barracuda09** [comment]
Hi FuNK3Y,

Thanks for this report and testing.

I have some questions:
- Is this a problem from the last time?
- A full restart of the cubox, is a power cycle or reboot

SatPI sees a lock on the signal (FE status 0x1F)  But indeed no pids receive data.:
```
48  Wed Apr 1 23:46:42.303012023 2015  6  [ Frontend.cpp:497] Stream: 0, Tuned and locked (FE status 0x1F).
```
And w_scan sees indeed also an lock but saying also:
```
Info: no data from NIT(actual)     (Don't realy know what this means)
```

**Comment by FuNK3Y** [comment]
I did some more testing, and as you mentioned the problem lies within the driver.

I tested with tvheadend as well and it only detected half of the tuners & so on. A reboot (not a power cycle) solves it.

As I do have 2 time the same tuner, I took one away; I'll see if it helps.

SATPI is clearly not responsible for this one :+1:
