### ISSUE TITLE
no webif

### ISSUE THREAD

**Issue by etmmast** [Barracuda09/SATPI#35]
Hi,

i just installed the satip software on a ubuntu server, when i start the webif i will work for 10 seconds and then the page/site is not found any longer

whats wrong?

thanks Marco

**Comment by Barracuda09** [comment]
Hi Marco,

A few questions
 - does SatPI stop all together
 - which browser
 - what does syslog say

Marc

**Comment by Barracuda09** [comment]
Hi Marco,

I had a few questions, can you please provide the answers? To help improve SatPI

Thanks,

Marc

**Comment by etmmast** [comment]
I will answer tomorro. 

 

Thanks

 

Gr. Marco

 

Van: Marc [mailto:notifications@github.com] 
Verzonden: dinsdag 7 april 2015 12:37
Aan: Barracuda09/SATPI
CC: etmmast
Onderwerp: Re: [SATPI] no webif (#35)

 

Hi Marco,

I had a few questions, can you please provide the answers? To help improve SatPI

Thanks,

Marc

**Comment by Barracuda09** [comment]
I Don't see any problems with this.. I will close it for now.
