### ISSUE TITLE
DVB artefact using SatPI ?

### ISSUE THREAD

**Issue by zz64** [Barracuda09/SATPI#37]
Hi, i have successfully built 1.5 version with openwrt mips32 for brcm63xx, but i can't play any frequency :(
trying to play:
rtsp://192.168.3.57:554/?freq=11240&sr=27500&pol=v&msys=dvbs&pids=all
or
rtsp://192.168.3.57:554/?freq=11240&sr=27500&pol=v&msys=dvbs&pids=0,247,248,249
daemon log here : http://pastebin.com/raw.php?i=6s90ftpa

![satpi_1 5](https://cloud.githubusercontent.com/assets/1113878/11238022/520f21c0-8de3-11e5-831c-5ed5b9838e58.png)

i try to build latest master,but fail :(
http://pastebin.com/raw.php?i=isCJqzcx
any idea ?
Thanks.

**Comment by Barracuda09** [comment]
Hi,

If you build without LIBDVBCSA=yes

**Comment by zz64** [comment]
Ok, i try this next..
but please, 1.5 version (from releases) not work ?
Thanks.

**Comment by Barracuda09** [comment]
Sorry.. maybe not.. master should work.

**Comment by zz64** [comment]
without DVBCSA the master built ok :)

**Comment by Barracuda09** [comment]
Ok.. but this should work also 'make debug LIBDVBCSA=yes'

**Comment by zz64** [comment]
Work but 98% Continuity errors :\
i think is not ready yes ?

![satpi_vlc](https://cloud.githubusercontent.com/assets/1113878/11240844/0fc9d9be-8df6-11e5-9a1d-9c76bdbeb0fb.png)

![satpi_on_master](https://cloud.githubusercontent.com/assets/1113878/11240815/d4e7051a-8df5-11e5-9600-18017e783742.png)

**Comment by Barracuda09** [comment]
Well it should work okay. what is the load of the processor?

**Comment by zz64** [comment]
not over 50%
![satpi_cpu_load](https://cloud.githubusercontent.com/assets/1113878/11241036/9d7e9e56-8df7-11e5-906f-e889aa30dcde.png)

**Comment by zz64** [comment]
0 Continuity errors using tvheadend (4.1) on this hardware (with same channel).

**Comment by Barracuda09** [comment]
How did you start SatPI?

**Comment by zz64** [comment]
satpi in rootfs
the "web" folder found in /satpi/web

**Comment by zz64** [comment]
using tvheadend on same hardware:

![tvheadend_4 1_nb6media](https://cloud.githubusercontent.com/assets/1113878/11241399/bf95bf94-8dfa-11e5-9fa0-31e851c546e4.png)

**Comment by Barracuda09** [comment]
What does syslog say?

because logd was also 12%

**Comment by zz64** [comment]
http://pastebin.com/raw.php?i=FzdAdrbg

**Comment by Barracuda09** [comment]
Okay there is the source of the problem.. why it is doing this I’m not sure
yet.

You stopped TvHeadend I assume.

**Comment by Barracuda09** [comment]
Could you remove in RtpThread.cpp line 266 (PERROR("send RTP");)
and check again?

**Comment by zz64** [comment]
openwrt tree need patch, i can't modify source manually.
can you provide patch please ?

**Comment by Barracuda09** [comment]
Hope this works

--- a/src/RtpThread.cpp
+++ b/src/RtpThread.cpp
@@ -263,6 +263,6 @@ void RtpThread::sendRtpPacket(RtpPacketBuffer &buffer,
const StreamClient &clien
        // send the RTP packet
        if (sendto(_socket_fd, rtpBuffer, size + RTP_HEADER_LEN,
MSG_DONTWAIT,
                          (struct sockaddr *)&client.getRtpSockAddr(),
sizeof(client.getRtpSockAddr())) == -1) {
-               PERROR("send RTP");
+//             PERROR("send RTP");
        }
 }

**Comment by zz64** [comment]
i can't copy paste from your reply.
can you attach "raw txt" please ?

**Comment by Barracuda09** [comment]
This Okay

[temp.patch.txt](https://github.com/Barracuda09/SATPI/files/37884/temp.patch.txt)

**Comment by zz64** [comment]
Applying ./patches/01-rtp-thread-remove-send-rtp.patch using plaintext: 
patching file src/RtpThread.cpp
Hunk #1 FAILED at 263.
1 out of 1 hunk FAILED -- saving rejects to file src/RtpThread.cpp.rej
Patch failed!  Please fix ./patches/01-rtp-thread-remove-send-rtp.patch!

**Comment by zz64** [comment]
ok, i make a patch myself.

**Comment by zz64** [comment]
patch ok, i build firmware now.

**Comment by zz64** [comment]
same problem :/

syslog: http://pastebin.com/raw.php?i=kz6kw8zY

![satpi_2](https://cloud.githubusercontent.com/assets/1113878/11244435/db30d9ce-8e0d-11e5-9651-604f0144a882.png)

**Comment by Barracuda09** [comment]
Sorry could you try to change in RtpThread.cpp same place:

	// send the RTP packet
	if (sendto(_socket_fd, rtpBuffer, size + RTP_HEADER_LEN, MSG_DONTWAIT,
			  (struct sockaddr *)&client.getRtpSockAddr(), sizeof(client.getRtpSockAddr())) == -1) {
		PERROR("send RTP");
	}

change MSG_DONTWAIT to MSG_NOSIGNAL 

The packets get not send because it does not wait for completion.

**Comment by Barracuda09** [comment]
Hi,

Can you please give me the results of these cmd:
cat /proc/sys/net/core/wmem_default
cat /proc/sys/net/core/wmem_max

Thanks for you efforts

**Comment by zz64** [comment]
Hi,
1) changing MSG_DONTWAIT to MSG_NOSIGNAL not solve the problem.

2) #cat /proc/sys/net/core/wmem_default
163840
cat /proc/sys/net/core/wmem_max
163840

please, if you want quick progress, you must add a "test branch". then you fix what seems solving the issue in this branch.
I will use this branch for testing. no patch no modification...

**Comment by Barracuda09** [comment]
Hi,

Thanks for your support.
Can you try a quick test by incrementing the buffer with:
sudo sysctl -w net.core.wmem_default=524288

**Comment by zz64** [comment]
root@nb6media:~# sysctl -w net.core.wmem_default=524288
net.core.wmem_default = 524288
root@nb6media:~# cat /proc/sys/net/core/wmem_default
524288

no change :\

syslog: http://pastebin.com/raw.php?i=ad6aHC8r

**Comment by Barracuda09** [comment]
sorry.. there is also an max value..
sudo sysctl -w net.core.wmem_max=524288

**Comment by zz64** [comment]
root@nb6media:/satpi# sysctl -w net.core.wmem_default=524288
net.core.wmem_default = 524288
root@nb6media:/satpi# cat /proc/sys/net/core/wmem_max
524288

no change :\

**Comment by Barracuda09** [comment]
There is also an DVR buffer size in the frontend webpage... try incrementing this...
else I have no idea at the moment what it could be.

I run it on a RPI2 with no problems.. just like it is in master.

Again thanks for you efforts for now.

**Comment by zz64** [comment]
incrementing "DVR buffer size" no solve... :\

i can't compile SatPI with uClibc
log: http://pastebin.com/raw.php?i=QYjNYfkz

any solution to get SatPI compile with uClibc ? (because is the default library used in OpenWrt distrib).

Thanks.

**Comment by Barracuda09** [comment]
Hi,

Sorry.. not out of the box. But you can try to remove:
pthread_setname_np(_thread, _name.c_str());

and try again. to see what is missing more from uClibc.

**Comment by zz64** [comment]
compile ok without pthread_setname_np...

here my contribution: http://dl.free.fr/iDa30Zqrw
SatPI Makefile for OpenWRT
please add it in your repository. (because "dl.free.fr" delete files after 30 days)

Thanks

**Comment by Barracuda09** [comment]
Hi, Thanks for you contribution. But I can not downloaded it... Sorry I do not understand the France
language.

**Comment by zz64** [comment]
can't attach file here (on github only image, txt, pdf... files allowed).
can you provide a place where i put this file ?

**Comment by Barracuda09** [comment]
I have extracted the file (google translate is my friend).. Many thanks I will look how to put it into
the repo.

**Comment by zz64** [comment]
Hi, I think I found the anomaly. when i launch SatPI i get message in kernel log:
``
ttusb2: there might have been an error during control message transfer. (rlen = 4, was 3)
``
full log: http://pastebin.com/raw.php?i=GV414XuQ

(this error not found when starting tvheadend)
log: http://pastebin.com/raw.php?i=TumuZN1P

i think the SatPI puts a "wrong parameter" in the kernel drivers ?
can we fix this problem ?

kernel information:
``
root@nb6media:/# uname -a

Linux nb6media 3.10.49 #5 Tue Nov 10 16:27:23 CET 2015 mips GNU/Linux
``

Thanks.

**Comment by Barracuda09** [comment]
Hi,

Thanks for your support so far!.
And if you tune to an frequency. Do you see more of these message?

**Comment by zz64** [comment]
No, only when first launch

**Comment by zz64** [comment]
is not dvbapi version related ?

**Comment by Barracuda09** [comment]
That could be the case.. you can find the version somewhere in 'linux/dvb/version.h'

**Comment by Barracuda09** [comment]
But it shows up 'correctly' in the frontend.html..

**Comment by zz64** [comment]
``
linux-brcm63xx_generic/linux-3.10.49$ find . -type d -name dvb
./Documentation/DocBook/media/dvb
./Documentation/dvb
./include/config/dvb
./include/uapi/linux/dvb
./user_headers/include/linux/dvb

linux-brcm63xx_generic/linux-3.10.49$ cat  ./include/uapi/linux/dvb/version.h
/*
 * version.h
 *
 * Copyright (C) 2000 Holger Waechtler <holger@convergence.de>
 *                    for convergence integrated media GmbH
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

#ifndef _DVBVERSION_H_
#define _DVBVERSION_H_

#define DVB_API_VERSION 5
#define DVB_API_VERSION_MINOR 10

#endif /*_DVBVERSION_H_*/
``

**Comment by zz64** [comment]
the dvb include's is in "./include/uapi/linux/dvb" Not "linux/dvb/version.h"

**Comment by Barracuda09** [comment]
Yes.. do you have by any chance another DVB card you could try?

And try making a debug version of SatPI, It gives some more info.

**Comment by zz64** [comment]
no, i have only this :\

**Comment by Barracuda09** [comment]
Well It should work with this one too...

**Comment by Barracuda09** [comment]
Hi Again,

How does it work with HTTP streaming from resent changes?

Thanks for testing,

Marc

**Comment by Barracuda09** [comment]
I will close this issue for now. If someone sees this, please make a new issue.

**Comment by Barracuda09** [comment]
Hi @zz64 

Sorry, could you try to 'upload'  the SatPI Makefile for OpenWRT again?

I lost it unfortunately, thanks for your support up until now.

Regards,

Marc
