### ISSUE TITLE
100% cpu usage on 2 processes

### ISSUE THREAD

**Issue by joolzg** [Barracuda09/SATPI#45]
Just built a clean version for the 1st time and did the ./satpi

htop shows me 2 satpis running at 99.9 and 100% cpu usage

**Comment by Barracuda09** [comment]
Hi,

A few questions:
- how did you build  SatPI
- what or is it streaming
- what is the log showing
- what system do you use

Thanks for trying!

**Comment by joolzg** [comment]
Build using the the Makefile

not even got that far all I did was run it and check the web page was available before going any further.

Its a clean machine with a quad tbs dvb-s/s2 card in

**Comment by Barracuda09** [comment]
Make debug or just make?

What is the log say?
Op 20 jan. 2016 18:27 schreef "Julian Gardner" <notifications@github.com>
het volgende:

**Comment by joolzg** [comment]
just did a make and

./satpi

Where is the log

**Comment by Barracuda09** [comment]
First of all are you running as root?
Second if you have a problem you should do a make debug it has more info
for me.

The log is in de web page (limited) or in syslog.

Thanks for testing.

**Comment by Barracuda09** [comment]
I will close this issue for now. If someone has problems please make a new issue.
