### ISSUE TITLE
SCR Support 

### ISSUE THREAD

**Issue by goerdi** [Barracuda09/SATPI#46]
Hi !
is Unicable Support planned ?

ciao Gerd

**Comment by Barracuda09** [comment]
Hi,

I would like to implement this.

**Comment by goerdi** [comment]
I guess therefore you need a config file..... :)

**Comment by Barracuda09** [comment]
Hi @goerdi 

I have done some work on this. You could try it out if you like.
It is still a work in progress but should work at this point (only PIN is not implemented yet)

Regards,

Marc

**Comment by goerdi** [comment]
Hi !  i'll try but i'm tired to restore config every time... so i need some command line options o a config file...

Ciao Gerd

**Comment by Barracuda09** [comment]
Yes I know it can be annoying at times.
I am working on an solution, but sorry my time limited at the moment.

Thanks for giving this a try.

Marc

**Comment by goerdi** [comment]
Hi maybe you store ist in the xml of the Webserver

Ciao Gerd


Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 2. August 2016 10:31:38 vorm. schrieb Marc <notifications@github.com>:

**Comment by Barracuda09** [comment]
Hi @goerdi 

The config is saved now and reloaded by startup again. 
So it should be more easy to test it now.

Thanks for giving this a try,
Marc

**Comment by Barracuda09** [comment]
I will close this issue for now, as it is fixed for some time.

Please make an new issue if there are problems regarding SCR support.
