### ISSUE TITLE
Not working with DVBViewer Pro

### ISSUE THREAD

**Issue by bbtimx** [Barracuda09/SATPI#48]
Hey

In the Log I see my DVBViewer Pro connects to SATIP but I get no Picture ..
After a while I get an memory access error!

**Comment by Barracuda09** [comment]
Hi,

Yes thanks for pointing this out.. I Will fix this.
DId not try this out for some time.

**Comment by Barracuda09** [comment]
Please give it a try

**Comment by bbtimx** [comment]
Hey,

It´s working fine now. Thanks a lot :)

But the auto search only shows SatIP Server entry after 20s of waiting and the UDP TCP selcet disappear.

![image](https://cloud.githubusercontent.com/assets/4718129/15247042/bd7e864e-1911-11e6-8275-756fd53f2edc.png)

![image](https://cloud.githubusercontent.com/assets/4718129/15247083/01ab76e2-1912-11e6-8eb0-da323cdecd26.png)

**Comment by Barracuda09** [comment]
Initial report is fixed. Will close this for now.
