### ISSUE TITLE
BOOTID fixed value

### ISSUE THREAD

**Issue by 9000h** [Barracuda09/SATPI#5]
in ssdp.c BOOTID.UPNP.ORG: 2318

the Spec says
The BOOTID.UPNP.ORG value shall increase each time that the device first announces on the network. It shall be stored in non-volatile memory

so it may need  to get stored in a file

**Comment by Barracuda09** [comment]
Hi 9000h,

I have added this feature, so if you like and you have some time you can try it

Thanks for testing,

Marc

**Comment by Barracuda09** [comment]
added this feature
