### ISSUE TITLE
Documentation update for DVB-T

### ISSUE THREAD

**Issue by yglodt** [Barracuda09/SATPI#52]
It would be great to document the parameters needed to open a DVB-T stream in vlc.

E.g. for the following:

![tv](https://cloud.githubusercontent.com/assets/489599/23092546/634bf5f8-f5c5-11e6-9111-b9628c2f5b3b.png)

**Comment by Barracuda09** [comment]
Hi @yglodt 

I think it should be something like this
```
http://ip.of.your.box:8875/?freq=522&bw=8&msys=dvbt&tmode=8k&mtype=64qam&gi=116&fec=23&pids=0,1,16,17,18,....
```

pids you have to add which apply to the channel you like to see or use pids=all

Regards,

Marc

**Comment by yglodt** [comment]
Yes this works! Thanks! To play back a 1080p-channel on my Pi 1+ it takes like 90% cpu and it's jerky. Probably the old Pi is just too weak :)

**Comment by Barracuda09** [comment]
Yes, I use a Pi 2. That has more power.
