### ISSUE TITLE
Changing LNB settings - not sticking (Press enter to save)

### ISSUE THREAD

**Issue by Benoire** [Barracuda09/SATPI#54]
Hi

I'm trying to change the LNB settings to align with the New Zealand Sky supplied LNBs frequency of L:10750,H:10750,S:0 but every time I go in to the settings of LNB0 on the first tuner it accepts the changes but quickly resets to something else if I click elsewhere on the screen or change tab.  This issue is repeated across all the tuners in the system.

As I can't find a save button for LNB config, am I doing something wrong?

Thanks,

Chris

**Comment by Barracuda09** [comment]
Hi,

Thanks for trying SatPi.

Well you should press "Enter" after changing the frequency.
Yes a save button should be an better way.

Hope this helps you out.

Kind regards,

Marc

Op 31 jul. 2017 11:32 a.m. schreef "Benoire" <notifications@github.com>:

**Comment by Benoire** [comment]
Wonderful thank you!  I didn't see a requirement for pressing Enter so didn't try it!

**Comment by Barracuda09** [comment]
Yes it is not intuitive. A save button would make it easier.

**Comment by Barracuda09** [comment]
Made a new issue for the 'Save' button see: #65
