### ISSUE TITLE
All output in a single line on SAT>IP Log Page with Safari web browser

### ISSUE THREAD

**Issue by pbriesch** [Barracuda09/SATPI#7]
Hi,

in Safari all output is in a single line which gets longer and longer. In Google Chrome and Firefox it works as it it supposed to.

**Comment by Barracuda09** [comment]
Thanks for you input. Sorry I never tried Safari.
Will see if I can fix this.

Marc

**Comment by Barracuda09** [comment]
If you like you can try it.

**Comment by pbriesch** [comment]
Hi Marc,

still does not work.

Paul

**Comment by Barracuda09** [comment]
Ok sorry.. I do not have Safari, I can not test this my self..

I will look into this. Thanks for trying.

Marc

**Comment by pbriesch** [comment]
Marc, thank you very much for your efforts!
Paul

**Comment by Barracuda09** [comment]
Hi,

Is this issue is fixed with latest commits?

Marc

**Comment by pbriesch** [comment]
Yes, it is!

What was the reason?

Paul

**Comment by Barracuda09** [comment]
Hi Paul,

Well problem was with the textareas - white-space attribute
