### ISSUE TITLE
How to advertize as DVB-C only

### ISSUE THREAD

**Issue by lars18th** [Barracuda09/SATPI#71]
Hi @Barracuda09 ,

I want to configure one SATPI instance with only `file` and `childpipe` inputs and advertized as DVB-C. 
The idea is to use only the `mapping.m3u` without any real tuner.

Any idea about how to achieve this?
Thank you.

**Comment by Barracuda09** [comment]
Hi @lars18th 

No at the moment you can only advertise as DVB-S2

**Comment by lars18th** [comment]
> No at the moment you can only advertise as DVB-S2

Ok. Thank you to comment it.
Regards.

**Comment by Barracuda09** [comment]
you could change it in the mean time in:
void TSReader::addDeliverySystemCount(..) -> _transform.advertiseAsDVBS2()

**Comment by lars18th** [comment]
> you could change it in the mean time in:
> void TSReader::addDeliverySystemCount(..) -> _transform.advertiseAsDVBS2()

:+1: 
https://github.com/Barracuda09/SATPI/blob/b7f09c665e1b682e9cb1ab30071d63a26a86f4a4/src/input/childpipe/TSReader.cpp#L89

Thank you!

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

Previous to close this issue (it's resolved) I ask if you want to add to the option to advertize as DVB-T (and/or DVB-T2). I feel it will be also useful.

Regards.

**Comment by lars18th** [comment]
All is done. So I close the issue.
Thank you!
