### ISSUE TITLE
Sugestion: Home UI page

### ISSUE THREAD

**Issue by lars18th** [Barracuda09/SATPI#88]
Hi @Barracuda09 ,

I feel it will be desisable to print additional info the HOME PAGE. For example the listening RTP PORT and the ADDRESS.

You agree?

**Comment by lars18th** [comment]
Hi @Barracuda09 ,

I update this old request: Inside the "Server Info Page" I suggest to print the listening address and ports (RTSP & HTTP), plus if the SSDP is enabled or not. That's the only missing info that I see inside the UI.

Thank you!

**Comment by Barracuda09** [comment]
Implemented by @issue  Many thanks for your support.

Will close this one.

**Comment by lars18th** [comment]
> Implemented by @issue Many thanks for your support.

I hope will be soon a PR & merge of the contribution from @issue :wink:

**Comment by Barracuda09** [comment]
@lars18th 

It is merged already, It requires to update the web directory.
