### ISSUE TITLE
crash on pids=all

### ISSUE THREAD

**Issue by 9000h** [Barracuda09/SATPI#9]
when try to use vlc to open rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all it will crash

in this mode you can select a different program inside vlc 

Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 0 --- starting ---
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 1 Not the preferred DVB API version, for correct function it should be 5.5 or higher
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 2 current DVB_API_VERSION: 5.4
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 3 Detecting frontends in: /dev/dvb
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 4 Frontends found: 4
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 5 Frontend Name: Philips TDA10023 DVB-C
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 6 Frontend Name: Montage RS6000(DVBSky)
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 7 Frontend Name: Montage RS6000(DVBSky)
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 8 Frontend Name: DRXK DVB-C DVB-T
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 9 eth0: 192.168.178.133 [00:40:ca:a2:c7:9d]
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 10 Setting up RTSP server
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 11 Setting up HTTP server
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 12 Setting up 8 RTP servers
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 13 Setting up 8 RTCP servers
Jan 27 00:29:35 yavdr2 SatIP Server[15812]: 14 Setting up SSDP server
Jan 27 00:30:11 yavdr2 SatIP Server[15812]: 15 RTSP Connection from 192.168.178.130 Port 62795
Jan 27 00:30:11 yavdr2 SatIP Server[15812]: 16 Frontend: 0, With SYS_DVBC_ANNEX_A Attaching dynamically to client 192.168.178.130
Jan 27 00:30:11 yavdr2 SatIP Server[15812]: 17 Setup Message
Jan 27 00:30:11 yavdr2 SatIP Server[15812]: 18 Modify Transport Parameters
Jan 27 00:30:11 yavdr2 SatIP Server[15812]: 19 Frontend: 0, Opened FE fd: 24.
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 20 Frontend: 0, Waiting on lock.
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 21 Frontend: 0, Not locked yet (FE status 0)...
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 22 Frontend: 0, Tuned and locked (FE status 31).
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 23 Frontend: 0, Opened DVR fd: 25.
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 24 Frontend: 0, Start streaming to 192.168.178.130 (54948 - 54949)
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 25 Frontend: 0, Start RTCP stream to 192.168.178.130 (54948 - 54949)
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 26 Frontend: 0, Open Frontend Monitor for 192.168.178.130 (54948 - 54949)
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 27 Setup Message
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 28 Modify Transport Parameters
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 29 Setup Message
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 30 Modify Transport Parameters
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 31 Setup Message
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 32 Modify Transport Parameters
Jan 27 00:30:12 yavdr2 SatIP Server[15812]: 33 Play Message
Jan 27 00:31:52 yavdr2 SatIP Server[15812]: 34 Frontend: 0, Teardown Message, gracefull: 1
Jan 27 00:31:52 yavdr2 SatIP Server[15812]: 35 RTSP Connection from 192.168.178.130 Port 62796
Jan 27 00:31:52 yavdr2 kernel: [194905.142090] thread_rtsp[15813]: segfault at 30 ip 0000000000405ae6 sp 00007f4861ee2bd0 error 6 in satpi[400000+e000]

**Comment by 9000h** [comment]
with make debug
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 0 [satpi.c:235] --- starting ---
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 1 [tune.c:383] Not the preferred DVB API version, for correct function it should be 5.5 or higher
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 2 [tune.c:384] current DVB_API_VERSION: 5.4
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 3 [tune.c:386] Detecting frontends in: /dev/dvb
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 4 [tune.c:396] Frontends found: 4
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 5 [tune.c:461] Open FE fd: 4 readonly 1
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 6 [tune.c:117] Frontend Name: Philips TDA10023 DVB-C
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 7 [tune.c:158] Frontend Type: Cable (Annex A)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 8 [tune.c:172] Frontend Type Unknown: 18
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 9 [tune.c:177] Frontend Freq: 47000000 Hz to 862000000 Hz
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 10 [tune.c:178] Frontend srat: 451875 symbols/s to 7230000 symbols/s
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 11 [tune.c:461] Open FE fd: 4 readonly 1
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 12 [tune.c:117] Frontend Name: Montage RS6000(DVBSky)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 13 [tune.c:142] Frontend Type: Satellite (DVB-S)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 14 [tune.c:146] Frontend Type: Satellite (DVB-S2)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 15 [tune.c:177] Frontend Freq: 950000 Hz to 2150000 Hz
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 16 [tune.c:178] Frontend srat: 1000000 symbols/s to 45000000 symbols/s
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 17 [tune.c:461] Open FE fd: 4 readonly 1
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 18 [tune.c:117] Frontend Name: Montage RS6000(DVBSky)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 19 [tune.c:142] Frontend Type: Satellite (DVB-S)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 20 [tune.c:146] Frontend Type: Satellite (DVB-S2)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 21 [tune.c:177] Frontend Freq: 950000 Hz to 2150000 Hz
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 22 [tune.c:178] Frontend srat: 1000000 symbols/s to 45000000 symbols/s
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 23 [tune.c:461] Open FE fd: 4 readonly 1
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 24 [tune.c:117] Frontend Name: DRXK DVB-C DVB-T
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 25 [tune.c:158] Frontend Type: Cable (Annex A)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 26 [tune.c:172] Frontend Type Unknown: 18
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 27 [tune.c:150] Frontend Type: Terrestrial (DVB-T)
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 28 [tune.c:177] Frontend Freq: 47000000 Hz to 865000000 Hz
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 29 [tune.c:178] Frontend srat: 870000 symbols/s to 11700000 symbols/s
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 30 [connection.c:261] eth0: 192.168.178.133 [00:40:ca:a2:c7:9d]
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 31 [rtsp.c:895] Setting up RTSP server
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 32 [http.c:445] Setting up HTTP server
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 33 [rtp.c:343] Setting up 8 RTP servers
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 34 [rtcp.c:338] Setting up 8 RTCP servers
Jan 27 00:39:38 yavdr2 SatIP Server[15954]: 35 [ssdp.c:89] Setting up SSDP server
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 36 [connection.c:190] RTSP Connection from 192.168.178.130 Port 62830
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 37 [rtsp.c:791] OPTIONS rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all RTSP/1.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 38 CSeq: 2
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 39 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 40 --- LINE END ---
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 41 [rtsp.c:386] Frontend: 0, With SYS_DVBC_ANNEX_A Attaching dynamically to client 192.168.178.130
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 42 [rtsp.c:791] DESCRIBE rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all RTSP/1.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 43 CSeq: 3
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 44 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 45 Accept: application/sdp
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 46 --- LINE END ---
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 47 [rtsp.c:595] RTSP/1.0 200 OK
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 48 CSeq: 3
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 49 Content-Type: application/sdp
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 50 Content-Base: rtsp://192.168.178.133/
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 51 Content-Length: 498
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 52 --- LINE END ---
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 53 v=0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 54 o=- 5678901234 7890123456 IN IP4 192.168.178.133
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 55 s=SatIPServer:1 4
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 56 t=0 0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 57 m=video 0 RTP/AVP 33
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 58 c=IN IP4 0.0.0.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 59 a=control:stream=0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 60 a=fmtp:33 ver=1.2;tuner=1,0,0,0,338000,auto,SYS_DVBC_ANNEX_A,QAM_256,6900000,0,0,0,0;pids=0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 61 a=inactive
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 62 m=video 0 RTP/AVP 33
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 63 c=IN IP4 0.0.0.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 64 a=control:stream=1
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 65 a=fmtp:33 
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 66 a=inactive
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 67 m=video 0 RTP/AVP 33
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 68 c=IN IP4 0.0.0.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 69 a=control:stream=2
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 70 a=fmtp:33 
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 71 a=inactive
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 72 m=video 0 RTP/AVP 33
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 73 c=IN IP4 0.0.0.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 74 a=control:stream=3
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 75 a=fmtp:33 
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 76 a=inactive
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 77 [rtsp.c:791] SETUP rtsp://192.168.178.133/stream=0 RTSP/1.0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 78 CSeq: 4
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 79 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 80 Transport: RTP/AVP;unicast;client_port=62610-62611
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 81 --- LINE END ---
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 82 [rtsp.c:425] Setup Message
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 83 [rtsp.c:434] Modify Transport Parameters
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 84 [tune.c:461] Open FE fd: 24 readonly 0
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 85 [tune.c:517] Frontend: 0, Opened FE fd: 24.
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 86 [tune.c:349] Start tuning
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 87 [tune.c:528] Frontend: 0, Waiting on lock.
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 88 [tune.c:542] Frontend: 0, Not locked yet (FE status 0)...
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 89 [tune.c:539] Frontend: 0, Tuned and locked (FE status 31).
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 90 [tune.c:560] Frontend: 0, Opened DVR fd: 25.
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 91 [tune.c:497] Frontend: 0, Set filter PID 0 - fd 26
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 92 [rtcp.c:252] Frontend: 0, Start RTCP stream to 192.168.178.130 (62610 - 62611)
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 93 [rtcp.c:266] Frontend: 0, Open Frontend Monitor for 192.168.178.130 (62610 - 62611)
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 94 [tune.c:461] Open FE fd: 27 readonly 1
Jan 27 00:39:54 yavdr2 SatIP Server[15954]: 95 [rtp.c:98] Frontend: 0, Start streaming to 192.168.178.130 (62610 - 62611)
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 96 [rtsp.c:791] SETUP rtsp://192.168.178.133/stream=1 RTSP/1.0
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 97 CSeq: 5
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 98 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 99 Transport: RTP/AVP;unicast;client_port=53778-53779
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 100 Session: 00000000
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 101 --- LINE END ---
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 102 [rtsp.c:425] Setup Message
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 103 [rtsp.c:434] Modify Transport Parameters
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 104 [rtsp.c:791] SETUP rtsp://192.168.178.133/stream=2 RTSP/1.0
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 105 CSeq: 6
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 106 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 107 Transport: RTP/AVP;unicast;client_port=55762-55763
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 108 Session: 00000000
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 109 --- LINE END ---
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 110 [rtsp.c:425] Setup Message
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 111 [rtsp.c:434] Modify Transport Parameters
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 112 [rtsp.c:791] SETUP rtsp://192.168.178.133/stream=3 RTSP/1.0
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 113 CSeq: 7
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 114 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 115 Transport: RTP/AVP;unicast;client_port=59376-59377
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 116 Session: 00000000
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 117 --- LINE END ---
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 118 [rtsp.c:425] Setup Message
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 119 [rtsp.c:434] Modify Transport Parameters
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 120 [rtsp.c:791] PLAY rtsp://192.168.178.133/ RTSP/1.0
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 121 CSeq: 8
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 122 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 123 Session: 00000000
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 124 Range: npt=0.000-
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 125 --- LINE END ---
Jan 27 00:39:55 yavdr2 SatIP Server[15954]: 126 [rtsp.c:496] Play Message
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 127 [rtsp.c:791] TEARDOWN rtsp://192.168.178.133/ RTSP/1.0
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 128 CSeq: 9
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 129 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 130 Session: 00000000
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 131 --- LINE END ---
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 132 [rtsp.c:704] Frontend: 0, Teardown Message, gracefull: 1
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 133 [connection.c:190] RTSP Connection from 192.168.178.130 Port 62831
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 134 [rtsp.c:791] OPTIONS rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all RTSP/1.0
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 135 CSeq: 2
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 136 User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Jan 27 00:40:01 yavdr2 SatIP Server[15954]: 137 --- LINE END ---
Jan 27 00:40:01 yavdr2 kernel: [195393.799996] thread_rtsp[15955]: segfault at 30 ip 0000000000406917 sp 00007f5eeffb3d90 error 6 in satpi[400000+13000]

Core was generated by `./satpi --no-daemon'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000406917 in parse_channel_info_from (
    msg=0x7f5ed8001eb0 "OPTIONS rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all RTSP/1.0\r\nCSeq: 2\r\nUser-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)\r\n\r\n", client=0x6188e0, fe=0x618160) at rtsp.c:384
384								client->fe->attached = 1;
(gdb) bt
#0  0x0000000000406917 in parse_channel_info_from (
    msg=0x7f5ed8001eb0 "OPTIONS rtsp://192.168.178.133/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=all RTSP/1.0\r\nCSeq: 2\r\nUser-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)\r\n\r\n", client=0x6188e0, fe=0x618160) at rtsp.c:384
#1  0x0000000000407e32 in thread_work_rtsp (arg=0x618160) at rtsp.c:801
#2  0x00007f5ef0583e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f5ef00a92ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
(gdb)

**Comment by Barracuda09** [comment]
Hi 9000h,

The crash was not related to pids=all, but still not implemente

Thanks for testing,

Marc
